development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:f1d1cad7ca704b2ff02bfb63f32c3160@tetra.redistogo.com:9809/
  channel_prefix: messageapp_production
