development:
  adapter: async

test:
<<<<<<< HEAD
  adapter: async
=======
  adapter: test
>>>>>>> dc8077038e973d402628a4f9fe2989bbac6efe9c

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: messageapp_production
